apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-quarkus
  labels:
    app: java-quarkus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-quarkus
  template:
    metadata:
      labels:
        app: java-quarkus
    spec:
      containers:
      - name: java-quarkus
        image: registry.black-crab.cc/java-quarkus:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
